const path = require('path');
require('dotenv').config({ path: path.resolve(__dirname, '../.env') });
const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');

const prisma = new PrismaClient();

async function main() {
  console.log('--- Starting Urban Furniture Database Seeding ---');

  // ==========================================
  // 1. Chart of Accounts
  // ==========================================
  console.log('Seeding Chart of Accounts...');
  const accountsData = [
    { code: '1000', name: 'Cash in Hand', type: 'ASSET' },
    { code: '1010', name: 'Bank Account - HDFC', type: 'ASSET' },
    { code: '1100', name: 'Debtors / Accounts Receivable', type: 'ASSET' },
    { code: '1200', name: 'Inventory / Stock A/c', type: 'ASSET' },
    { code: '2000', name: 'Creditors / Accounts Payable', type: 'LIABILITY' },
    { code: '2100', name: 'Output GST / Tax Payable', type: 'LIABILITY' },
    { code: '2110', name: 'Input GST / Tax Credit Paid', type: 'ASSET' },
    { code: '3000', name: 'Capital / Owner Equity', type: 'EQUITY' },
    { code: '4000', name: 'Sales Income', type: 'INCOME' },
    { code: '5000', name: 'Purchases Expense', type: 'EXPENSE' },
    { code: '5100', name: 'Operating Expenses', type: 'EXPENSE' },
    { code: '5200', name: 'Other Expenses', type: 'OTHER_EXPENSE' },
  ];

  const accounts = {};
  for (const acc of accountsData) {
    accounts[acc.code] = await prisma.account.upsert({
      where: { code: acc.code },
      update: { name: acc.name, type: acc.type },
      create: acc,
    });
  }

  // ==========================================
  // 2. Journals
  // ==========================================
  console.log('Seeding Journals...');
  const journalsData = [
    {
      name: 'Customer Invoices / Sales Journal',
      code: 'INV',
      type: 'SALES',
      defaultDebitAccountId: accounts['1100'].id,
      defaultCreditAccountId: accounts['4000'].id,
    },
    {
      name: 'Vendor Bills / Purchase Journal',
      code: 'BILL',
      type: 'PURCHASE',
      defaultDebitAccountId: accounts['5000'].id,
      defaultCreditAccountId: accounts['2000'].id,
    },
    {
      name: 'Bank Journal',
      code: 'BNK',
      type: 'BANK',
      defaultDebitAccountId: accounts['1010'].id,
      defaultCreditAccountId: accounts['1010'].id,
    },
    {
      name: 'Cash Journal',
      code: 'CSH',
      type: 'CASH',
      defaultDebitAccountId: accounts['1000'].id,
      defaultCreditAccountId: accounts['1000'].id,
    },
    {
      name: 'General / Miscellaneous Journal',
      code: 'MISC',
      type: 'GENERAL',
      defaultDebitAccountId: null,
      defaultCreditAccountId: null,
    },
  ];

  for (const j of journalsData) {
    await prisma.journal.upsert({
      where: { code: j.code },
      update: j,
      create: j,
    });
  }

  // ==========================================
  // 3. Product Categories
  // ==========================================
  console.log('Seeding Product Categories...');
  const categoriesList = [
    'Chairs',
    'Tables',
    'Sofas',
    'Dining',
    'Office Furniture',
    'Storage',
    'Beds',
    'Combos & Bundles',
    'Services',
  ];

  const categories = {};
  for (const catName of categoriesList) {
    categories[catName] = await prisma.productCategory.upsert({
      where: { name: catName },
      update: {},
      create: { name: catName, description: `${catName} collection and furnishings` },
    });
  }

  // ==========================================
  // 4. Products (100 Records)
  // ==========================================
  console.log('Seeding 100 Products across 7 Segments...');
  const productsData = [
    // --- 1. Chairs & Ergonomic Seating (20 Products) ---
    {
      name: 'AeroMesh High-Back Ergonomic Chair',
      type: 'GOODS',
      salesPrice: 14500.0,
      costPrice: 8500.0,
      categoryName: 'Chairs',
      imageUrl: 'https://images.unsplash.com/photo-1580481077195-c3a8b49e1e32?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Executive Leather Boss Armchair',
      type: 'GOODS',
      salesPrice: 28500.0,
      costPrice: 17000.0,
      categoryName: 'Chairs',
      imageUrl: 'https://images.unsplash.com/photo-1505797149-43b0069ec26b?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'ProPosture Lumbar Support Task Chair',
      type: 'GOODS',
      salesPrice: 11200.0,
      costPrice: 6500.0,
      categoryName: 'Chairs',
      imageUrl: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: 'Immediate Payment',
      allowPartialPayment: false,
    },
    {
      name: 'Nordic Minimalist Oak Dining Chair',
      type: 'GOODS',
      salesPrice: 5800.0,
      costPrice: 3200.0,
      categoryName: 'Chairs',
      imageUrl: 'https://images.unsplash.com/photo-1592078615290-033ee584e267?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Velvet Wingback Accent Reading Chair',
      type: 'GOODS',
      salesPrice: 22000.0,
      costPrice: 13500.0,
      categoryName: 'Chairs',
      imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '15 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Drafting Stool with Foot Ring',
      type: 'GOODS',
      salesPrice: 7900.0,
      costPrice: 4600.0,
      categoryName: 'Chairs',
      imageUrl: 'https://images.unsplash.com/photo-1503602642458-232111445657?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: 'Immediate Payment',
      allowPartialPayment: false,
    },
    {
      name: 'Mid-Century Boucle Lounge Chair',
      type: 'GOODS',
      salesPrice: 18500.0,
      costPrice: 11000.0,
      categoryName: 'Chairs',
      imageUrl: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Industrial Metal & Walnut Bar Stool',
      type: 'GOODS',
      salesPrice: 4900.0,
      costPrice: 2800.0,
      categoryName: 'Chairs',
      imageUrl: 'https://images.unsplash.com/photo-1551298370-9d3d53740c72?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: 'Immediate Payment',
      allowPartialPayment: true,
    },
    {
      name: 'Ergonomic Kneeling Posture Chair',
      type: 'GOODS',
      salesPrice: 8400.0,
      costPrice: 4800.0,
      categoryName: 'Chairs',
      imageUrl: 'https://images.unsplash.com/photo-1580481077195-c3a8b49e1e32?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Rattan Cane Accent Lounge Armchair',
      type: 'GOODS',
      salesPrice: 13500.0,
      costPrice: 7800.0,
      categoryName: 'Chairs',
      imageUrl: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '15 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Stackable Conference Banquet Chair',
      type: 'GOODS',
      salesPrice: 3200.0,
      costPrice: 1800.0,
      categoryName: 'Chairs',
      imageUrl: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'E-Sports Gaming Chair with Headrest',
      type: 'GOODS',
      salesPrice: 16800.0,
      costPrice: 9900.0,
      categoryName: 'Chairs',
      imageUrl: 'https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: 'Immediate Payment',
      allowPartialPayment: false,
    },
    {
      name: 'Contemporary Swivel Tub Chair',
      type: 'GOODS',
      salesPrice: 19500.0,
      costPrice: 11500.0,
      categoryName: 'Chairs',
      imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Solid Teak Slat Back Dining Chair',
      type: 'GOODS',
      salesPrice: 6500.0,
      costPrice: 3800.0,
      categoryName: 'Chairs',
      imageUrl: 'https://images.unsplash.com/photo-1592078615290-033ee584e267?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Plush Velvet Counter Stool (Gold Base)',
      type: 'GOODS',
      salesPrice: 7200.0,
      costPrice: 4100.0,
      categoryName: 'Chairs',
      imageUrl: 'https://images.unsplash.com/photo-1551298370-9d3d53740c72?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '15 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Scandinavian Birch Rocking Chair',
      type: 'GOODS',
      salesPrice: 15400.0,
      costPrice: 8900.0,
      categoryName: 'Chairs',
      imageUrl: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Outdoor Weatherproof Patio Armchair',
      type: 'GOODS',
      salesPrice: 9500.0,
      costPrice: 5600.0,
      categoryName: 'Chairs',
      imageUrl: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Conference Leather Guest Sled Chair',
      type: 'GOODS',
      salesPrice: 8800.0,
      costPrice: 5100.0,
      categoryName: 'Chairs',
      imageUrl: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Antique Vintage Chesterfield Dining Chair',
      type: 'GOODS',
      salesPrice: 12500.0,
      costPrice: 7500.0,
      categoryName: 'Chairs',
      imageUrl: 'https://images.unsplash.com/photo-1580481077195-c3a8b49e1e32?w=500&auto=format&fit=crop&q=80',
      status: 'ARCHIVED',
      paymentTerms: '30 Days',
      allowPartialPayment: false,
    },
    {
      name: 'Ergonomic Breathable Active Saddle Stool',
      type: 'GOODS',
      salesPrice: 6200.0,
      costPrice: 3500.0,
      categoryName: 'Chairs',
      imageUrl: 'https://images.unsplash.com/photo-1503602642458-232111445657?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: 'Immediate Payment',
      allowPartialPayment: false,
    },

    // --- 2. Tables & Desks (20 Products) ---
    {
      name: 'Dual-Motor Electric Standing Desk 140cm',
      type: 'GOODS',
      salesPrice: 34000.0,
      costPrice: 20000.0,
      categoryName: 'Office Furniture',
      imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Solid Sheesham 6-Seater Dining Table',
      type: 'GOODS',
      salesPrice: 28000.0,
      costPrice: 16500.0,
      categoryName: 'Dining',
      imageUrl: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Executive Walnut Veneer L-Shaped Desk',
      type: 'GOODS',
      salesPrice: 48000.0,
      costPrice: 29000.0,
      categoryName: 'Office Furniture',
      imageUrl: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '60 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Italian Carrara White Marble Coffee Table',
      type: 'GOODS',
      salesPrice: 19500.0,
      costPrice: 11000.0,
      categoryName: 'Tables',
      imageUrl: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '15 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Minimalist WFH Oak Writing Desk',
      type: 'GOODS',
      salesPrice: 14500.0,
      costPrice: 8500.0,
      categoryName: 'Office Furniture',
      imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: 'Immediate Payment',
      allowPartialPayment: false,
    },
    {
      name: 'Extendable Scandinavian Dining Table 8-Seater',
      type: 'GOODS',
      salesPrice: 38000.0,
      costPrice: 22500.0,
      categoryName: 'Dining',
      imageUrl: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Boardroom Conference Table 12-Seater (Wire Mgmt)',
      type: 'GOODS',
      salesPrice: 95000.0,
      costPrice: 58000.0,
      categoryName: 'Office Furniture',
      imageUrl: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '60 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Geometric Brass & Glass Nesting Coffee Tables',
      type: 'GOODS',
      salesPrice: 12800.0,
      costPrice: 7200.0,
      categoryName: 'Tables',
      imageUrl: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '15 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Round Fluted Wood Bistro Dining Table',
      type: 'GOODS',
      salesPrice: 16500.0,
      costPrice: 9800.0,
      categoryName: 'Dining',
      imageUrl: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Industrial Reclaimed Wood Console Entryway Table',
      type: 'GOODS',
      salesPrice: 11900.0,
      costPrice: 6900.0,
      categoryName: 'Tables',
      imageUrl: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: 'Immediate Payment',
      allowPartialPayment: false,
    },
    {
      name: 'Compact Corner Study Computer Desk',
      type: 'GOODS',
      salesPrice: 8900.0,
      costPrice: 5200.0,
      categoryName: 'Office Furniture',
      imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: 'Immediate Payment',
      allowPartialPayment: false,
    },
    {
      name: 'Terrazzo Stone Top Cylinder Side Table',
      type: 'GOODS',
      salesPrice: 6800.0,
      costPrice: 3900.0,
      categoryName: 'Tables',
      imageUrl: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '15 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Solid Acacia Live-Edge Dining Table',
      type: 'GOODS',
      salesPrice: 42000.0,
      costPrice: 25000.0,
      categoryName: 'Dining',
      imageUrl: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Modular Collaborative Workstation Table 4-Person',
      type: 'GOODS',
      salesPrice: 52000.0,
      costPrice: 31000.0,
      categoryName: 'Office Furniture',
      imageUrl: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '60 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Black Tempered Glass Sofa End Table',
      type: 'GOODS',
      salesPrice: 5400.0,
      costPrice: 3100.0,
      categoryName: 'Tables',
      imageUrl: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: 'Immediate Payment',
      allowPartialPayment: false,
    },
    {
      name: 'Outdoor Weatherproof Teak Coffee Table',
      type: 'GOODS',
      salesPrice: 13200.0,
      costPrice: 7800.0,
      categoryName: 'Tables',
      imageUrl: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Mid-Century Teak Drop-Leaf Kitchen Table',
      type: 'GOODS',
      salesPrice: 15800.0,
      costPrice: 9400.0,
      categoryName: 'Dining',
      imageUrl: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?w=500&auto=format&fit=crop&q=80',
      status: 'ARCHIVED',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Vintage Industrial Draughtsman Drafting Table',
      type: 'GOODS',
      salesPrice: 24500.0,
      costPrice: 14800.0,
      categoryName: 'Office Furniture',
      imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=500&auto=format&fit=crop&q=80',
      status: 'ARCHIVED',
      paymentTerms: '30 Days',
      allowPartialPayment: false,
    },
    {
      name: 'Modernist Round Travertine Center Table',
      type: 'GOODS',
      salesPrice: 31000.0,
      costPrice: 18500.0,
      categoryName: 'Tables',
      imageUrl: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Wall-Mounted Foldable Floating Desk',
      type: 'GOODS',
      salesPrice: 4800.0,
      costPrice: 2700.0,
      categoryName: 'Office Furniture',
      imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: 'Immediate Payment',
      allowPartialPayment: false,
    },

    // --- 3. Sofas & Lounges (18 Products) ---
    {
      name: 'Nordic 3-Seater High-Density Fabric Sofa',
      type: 'GOODS',
      salesPrice: 36000.0,
      costPrice: 21000.0,
      categoryName: 'Sofas',
      imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'L-Shaped Sectional Velvet Sofa (Left Facing)',
      type: 'GOODS',
      salesPrice: 62000.0,
      costPrice: 37000.0,
      categoryName: 'Sofas',
      imageUrl: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Classic Chesterfield Genuine Tan Leather Sofa',
      type: 'GOODS',
      salesPrice: 85000.0,
      costPrice: 52000.0,
      categoryName: 'Sofas',
      imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '60 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Scandinavian Reversible Daybed Lounger',
      type: 'GOODS',
      salesPrice: 28500.0,
      costPrice: 17000.0,
      categoryName: 'Sofas',
      imageUrl: 'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Convertible Click-Clack Sofa Cum Bed',
      type: 'GOODS',
      salesPrice: 24000.0,
      costPrice: 14500.0,
      categoryName: 'Sofas',
      imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: ' Immediate Payment',
      allowPartialPayment: true,
    },
    {
      name: 'Power-Motion Single Motor Leather Recliner',
      type: 'GOODS',
      salesPrice: 32000.0,
      costPrice: 19500.0,
      categoryName: 'Sofas',
      imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Plush Velvet 2-Seater Studio Loveseat',
      type: 'GOODS',
      salesPrice: 26000.0,
      costPrice: 15500.0,
      categoryName: 'Sofas',
      imageUrl: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '15 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Modular 5-Piece Cloud Sectional Couch',
      type: 'GOODS',
      salesPrice: 115000.0,
      costPrice: 69000.0,
      categoryName: 'Sofas',
      imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '60 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Japanese Minimalist Low Futon Sofa',
      type: 'GOODS',
      salesPrice: 21500.0,
      costPrice: 12800.0,
      categoryName: 'Sofas',
      imageUrl: 'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Oversized Boucle Round Ottoman Pouf',
      type: 'GOODS',
      salesPrice: 7800.0,
      costPrice: 4200.0,
      categoryName: 'Sofas',
      imageUrl: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: 'Immediate Payment',
      allowPartialPayment: false,
    },
    {
      name: 'Mid-Century Tufted 3-Seater Walnut Frame Sofa',
      type: 'GOODS',
      salesPrice: 44000.0,
      costPrice: 26000.0,
      categoryName: 'Sofas',
      imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Curved Boucle Sculptural Designer Couch',
      type: 'GOODS',
      salesPrice: 78000.0,
      costPrice: 47000.0,
      categoryName: 'Sofas',
      imageUrl: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '60 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Dual-Power Zero Gravity Home Theater Recliner',
      type: 'GOODS',
      salesPrice: 49000.0,
      costPrice: 29500.0,
      categoryName: 'Sofas',
      imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Outdoor Weatherproof All-Weather Rattan Sofa',
      type: 'GOODS',
      salesPrice: 38500.0,
      costPrice: 23000.0,
      categoryName: 'Sofas',
      imageUrl: 'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Square Storage Ottoman Bench (Fabric)',
      type: 'GOODS',
      salesPrice: 9200.0,
      costPrice: 5400.0,
      categoryName: 'Sofas',
      imageUrl: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: 'Immediate Payment',
      allowPartialPayment: false,
    },
    {
      name: 'Vintage Faux Suede Settee Bench',
      type: 'GOODS',
      salesPrice: 17500.0,
      costPrice: 10200.0,
      categoryName: 'Sofas',
      imageUrl: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=500&auto=format&fit=crop&q=80',
      status: 'ARCHIVED',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Compact 1-Seater Cozy Swivel Armchair',
      type: 'GOODS',
      salesPrice: 14800.0,
      costPrice: 8700.0,
      categoryName: 'Sofas',
      imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '15 Days',
      allowPartialPayment: true,
    },
    {
      name: 'U-Shaped Luxury Grand Living Room Sectional',
      type: 'GOODS',
      salesPrice: 148000.0,
      costPrice: 89000.0,
      categoryName: 'Sofas',
      imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '60 Days',
      allowPartialPayment: true,
    },

    // --- 4. Storage & Shelving (15 Products) ---
    {
      name: 'Mid-Century Modern Credenza Sideboard',
      type: 'GOODS',
      salesPrice: 32000.0,
      costPrice: 19000.0,
      categoryName: 'Storage',
      imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: '5-Tier Industrial Steel & Wood Open Bookcase',
      type: 'GOODS',
      salesPrice: 14500.0,
      costPrice: 8400.0,
      categoryName: 'Storage',
      imageUrl: 'https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: 'Immediate Payment',
      allowPartialPayment: false,
    },
    {
      name: 'Floating Wall-Mounted TV Media Entertainment Console',
      type: 'GOODS',
      salesPrice: 18500.0,
      costPrice: 10800.0,
      categoryName: 'Storage',
      imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: '3-Drawer Mobile Steel Under-Desk Pedestal',
      type: 'GOODS',
      salesPrice: 6800.0,
      costPrice: 3900.0,
      categoryName: 'Storage',
      imageUrl: 'https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: false,
    },
    {
      name: 'Sliding 3-Door Solid Oak Wardrobe with Mirrors',
      type: 'GOODS',
      salesPrice: 68000.0,
      costPrice: 41000.0,
      categoryName: 'Storage',
      imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '60 Days',
      allowPartialPayment: true,
    },
    {
      name: '6-Drawer Wide Bedroom Tallboy Dresser',
      type: 'GOODS',
      salesPrice: 27500.0,
      costPrice: 16500.0,
      categoryName: 'Storage',
      imageUrl: 'https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Fluted Glass Door Display Curio Cabinet',
      type: 'GOODS',
      salesPrice: 36000.0,
      costPrice: 22000.0,
      categoryName: 'Storage',
      imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Cushioned Entryway Shoe Storage Bench',
      type: 'GOODS',
      salesPrice: 8200.0,
      costPrice: 4800.0,
      categoryName: 'Storage',
      imageUrl: 'https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: 'Immediate Payment',
      allowPartialPayment: false,
    },
    {
      name: 'Wall Modular Floating Display Bookshelves (Set of 3)',
      type: 'GOODS',
      salesPrice: 4500.0,
      costPrice: 2400.0,
      categoryName: 'Storage',
      imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: 'Immediate Payment',
      allowPartialPayment: false,
    },
    {
      name: 'Industrial Mobile Bar Cart with Wine Rack',
      type: 'GOODS',
      salesPrice: 11500.0,
      costPrice: 6600.0,
      categoryName: 'Storage',
      imageUrl: 'https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '15 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Heavy-Duty Warehouse Storage Steel Rack',
      type: 'GOODS',
      salesPrice: 16800.0,
      costPrice: 9900.0,
      categoryName: 'Storage',
      imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Teak Bathroom Vanity Cabinet with Basin Cutout',
      type: 'GOODS',
      salesPrice: 22000.0,
      costPrice: 13200.0,
      categoryName: 'Storage',
      imageUrl: 'https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Ladder Shelf Plant & Decor Stand 4-Tier',
      type: 'GOODS',
      salesPrice: 5200.0,
      costPrice: 2900.0,
      categoryName: 'Storage',
      imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: 'Immediate Payment',
      allowPartialPayment: false,
    },
    {
      name: 'Vintage Carved Sheesham Trunk Chest',
      type: 'GOODS',
      salesPrice: 19800.0,
      costPrice: 12000.0,
      categoryName: 'Storage',
      imageUrl: 'https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?w=500&auto=format&fit=crop&q=80',
      status: 'ARCHIVED',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Lateral 4-Drawer Fireproof Office Filing Cabinet',
      type: 'GOODS',
      salesPrice: 38000.0,
      costPrice: 23500.0,
      categoryName: 'Storage',
      imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '60 Days',
      allowPartialPayment: true,
    },

    // --- 5. Beds & Bedroom (12 Products) ---
    {
      name: 'King Size Hydraulic Storage Platform Bed',
      type: 'GOODS',
      salesPrice: 56000.0,
      costPrice: 34000.0,
      categoryName: 'Beds',
      imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '60 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Solid Teak Wood Queen Size Platform Bed',
      type: 'GOODS',
      salesPrice: 42000.0,
      costPrice: 25000.0,
      categoryName: 'Beds',
      imageUrl: 'https://images.unsplash.com/photo-1540518614846-7ede433c4550?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Upholstered Wingback Tufted Headboard Bed',
      type: 'GOODS',
      salesPrice: 48000.0,
      costPrice: 29000.0,
      categoryName: 'Beds',
      imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Japanese Minimalist Low Tatami Bed Frame',
      type: 'GOODS',
      salesPrice: 34000.0,
      costPrice: 20500.0,
      categoryName: 'Beds',
      imageUrl: 'https://images.unsplash.com/photo-1540518614846-7ede433c4550?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Bedside Nightstand with Wireless Qi Charger',
      type: 'GOODS',
      salesPrice: 9500.0,
      costPrice: 5600.0,
      categoryName: 'Beds',
      imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: 'Immediate Payment',
      allowPartialPayment: false,
    },
    {
      name: 'Solid Oak 2-Drawer Floating Bedside Table',
      type: 'GOODS',
      salesPrice: 6500.0,
      costPrice: 3700.0,
      categoryName: 'Beds',
      imageUrl: 'https://images.unsplash.com/photo-1540518614846-7ede433c4550?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '15 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Dressing Vanity Console with LED Touch Mirror',
      type: 'GOODS',
      salesPrice: 26000.0,
      costPrice: 15500.0,
      categoryName: 'Beds',
      imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Bunk Bed Solid Pine with Safety Ladder',
      type: 'GOODS',
      salesPrice: 38000.0,
      costPrice: 23000.0,
      categoryName: 'Beds',
      imageUrl: 'https://images.unsplash.com/photo-1540518614846-7ede433c4550?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Canopy Four-Poster Matte Black Steel Bed',
      type: 'GOODS',
      salesPrice: 52000.0,
      costPrice: 31000.0,
      categoryName: 'Beds',
      imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '60 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Foldable Wall-Mounted Murphy Bed Single',
      type: 'GOODS',
      salesPrice: 46000.0,
      costPrice: 28000.0,
      categoryName: 'Beds',
      imageUrl: 'https://images.unsplash.com/photo-1540518614846-7ede433c4550?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Orthopedic Pocket-Spring King Mattress 10-Inch',
      type: 'GOODS',
      salesPrice: 32000.0,
      costPrice: 18500.0,
      categoryName: 'Beds',
      imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Antique Colonial Sheesham Poster Bed',
      type: 'GOODS',
      salesPrice: 65000.0,
      costPrice: 40000.0,
      categoryName: 'Beds',
      imageUrl: 'https://images.unsplash.com/photo-1540518614846-7ede433c4550?w=500&auto=format&fit=crop&q=80',
      status: 'ARCHIVED',
      paymentTerms: '60 Days',
      allowPartialPayment: true,
    },

    // --- 6. Combos & Curated Bundles (5 Products, type: COMBO) ---
    {
      name: 'Executive Office Suite Setup (Desk + Chair + Credenza)',
      type: 'COMBO',
      salesPrice: 95000.0,
      costPrice: 55000.0,
      categoryName: 'Combos & Bundles',
      imageUrl: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '60 Days',
      allowPartialPayment: true,
    },
    {
      name: 'WFH Ergonomic Productivity Nook (Standing Desk + AeroMesh)',
      type: 'COMBO',
      salesPrice: 44000.0,
      costPrice: 25000.0,
      categoryName: 'Combos & Bundles',
      imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Complete 6-Person Dining Ensemble (Table + 6 Chairs + Sideboard)',
      type: 'COMBO',
      salesPrice: 88000.0,
      costPrice: 51000.0,
      categoryName: 'Combos & Bundles',
      imageUrl: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '60 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Modern Living Room Trio (3-Seater Sofa + Marble Table + Console)',
      type: 'COMBO',
      salesPrice: 72000.0,
      costPrice: 42000.0,
      categoryName: 'Combos & Bundles',
      imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Luxury Master Bedroom Suite (Bed + 2 Nightstands + 6-Drawer Dresser)',
      type: 'COMBO',
      salesPrice: 135000.0,
      costPrice: 78000.0,
      categoryName: 'Combos & Bundles',
      imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '60 Days',
      allowPartialPayment: true,
    },

    // --- 7. Professional Services (10 Products, type: SERVICE) ---
    {
      name: '3D Interior Space Planning & Layout Service',
      type: 'SERVICE',
      salesPrice: 15000.0,
      costPrice: 5000.0,
      categoryName: 'Services',
      imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: 'Immediate Payment',
      allowPartialPayment: false,
    },
    {
      name: 'White-Glove On-Site Assembly & Installation',
      type: 'SERVICE',
      salesPrice: 2500.0,
      costPrice: 1200.0,
      categoryName: 'Services',
      imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: 'Immediate Payment',
      allowPartialPayment: false,
    },
    {
      name: 'Bespoke Custom Furniture Design & Woodcrafting',
      type: 'SERVICE',
      salesPrice: 35000.0,
      costPrice: 18000.0,
      categoryName: 'Services',
      imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Annual Corporate Furniture Maintenance & Polish AMC',
      type: 'SERVICE',
      salesPrice: 28000.0,
      costPrice: 12000.0,
      categoryName: 'Services',
      imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '60 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Commercial Workplace Ergonomic Audit & Assessment',
      type: 'SERVICE',
      salesPrice: 12000.0,
      costPrice: 4000.0,
      categoryName: 'Services',
      imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: false,
    },
    {
      name: 'Acoustic Soundproofing Wall Paneling Installation',
      type: 'SERVICE',
      salesPrice: 22000.0,
      costPrice: 11000.0,
      categoryName: 'Services',
      imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Premium Leather & Fabric Reupholstery Service',
      type: 'SERVICE',
      salesPrice: 18000.0,
      costPrice: 9000.0,
      categoryName: 'Services',
      imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Antique Furniture Conservation & Restoration Service',
      type: 'SERVICE',
      salesPrice: 25000.0,
      costPrice: 12500.0,
      categoryName: 'Services',
      imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=80',
      status: 'ARCHIVED',
      paymentTerms: '30 Days',
      allowPartialPayment: true,
    },
    {
      name: 'Architectural Lighting & Furniture Integration Consultancy',
      type: 'SERVICE',
      salesPrice: 16000.0,
      costPrice: 6500.0,
      categoryName: 'Services',
      imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: '15 Days',
      allowPartialPayment: false,
    },
    {
      name: 'Express 24-Hour Relocation & Furniture Disassembly',
      type: 'SERVICE',
      salesPrice: 8500.0,
      costPrice: 4200.0,
      categoryName: 'Services',
      imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
      paymentTerms: 'Immediate Payment',
      allowPartialPayment: false,
    },
  ];

  for (const prod of productsData) {
    const cat = categories[prod.categoryName];
    if (!cat) continue;
    const existing = await prisma.product.findFirst({ where: { name: prod.name } });
    if (!existing) {
      await prisma.product.create({
        data: {
          name: prod.name,
          type: prod.type,
          salesPrice: prod.salesPrice,
          costPrice: prod.costPrice,
          categoryId: cat.id,
          imageUrl: prod.imageUrl,
          status: prod.status,
          paymentTerms: prod.paymentTerms,
          allowPartialPayment: prod.allowPartialPayment,
        },
      });
    } else {
      await prisma.product.update({
        where: { id: existing.id },
        data: {
          type: prod.type,
          salesPrice: prod.salesPrice,
          costPrice: prod.costPrice,
          categoryId: cat.id,
          imageUrl: prod.imageUrl,
          status: prod.status,
          paymentTerms: prod.paymentTerms,
          allowPartialPayment: prod.allowPartialPayment,
        },
      });
    }
  }

  // ==========================================
  // 5. Contacts (Vendors + 100 Customers)
  // ==========================================
  console.log('Seeding Vendors...');
  const vendorsData = [
    {
      name: 'Azure Furniture',
      type: 'VENDOR',
      email: 'vendor@azurefurniture.com',
      mobile: '+91 9876543210',
      street: '42 Industrial Area, Phase 2',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      pincode: '400013',
      imageUrl: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Rahul Sharma',
      type: 'VENDOR',
      email: 'rahul.sharma@example.com',
      mobile: '+91 9090090909',
      street: '15 Civil Lines',
      city: 'Delhi',
      state: 'Delhi',
      country: 'India',
      pincode: '110054',
      imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
  ];

  const contacts = {};
  for (const v of vendorsData) {
    contacts[v.name] = await prisma.contact.upsert({
      where: { email: v.email },
      update: v,
      create: v,
    });
  }

  console.log('Seeding 100 Customers (40 Male, 40 Female, 20 Corporate; 70 India, 30 Foreign)...');
  const customersData = [
    // -------------------------------------------------------------
    // SECTION A: 40 MALE CUSTOMERS (35 Domestic India + 5 Foreign)
    // -------------------------------------------------------------
    // North India (10 Male)
    {
      name: 'Aarav Sharma',
      type: 'CUSTOMER',
      email: 'aarav.sharma@urbanclient.in',
      mobile: '+91 9810123451',
      street: 'B-14 Hauz Khas Enclave',
      city: 'Delhi',
      state: 'Delhi',
      country: 'India',
      pincode: '110016',
      imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Vikram Malhotra',
      type: 'CUSTOMER',
      email: 'vikram.malhotra@urbanclient.in',
      mobile: '+91 9811234562',
      street: '402 Golf Course Road, DLF Phase 5',
      city: 'Gurgaon',
      state: 'Haryana',
      country: 'India',
      pincode: '122002',
      imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Kabir Mehta',
      type: 'CUSTOMER',
      email: 'kabir.mehta@urbanclient.in',
      mobile: '+91 9812345673',
      street: 'Tower 4, Sector 62',
      city: 'Noida',
      state: 'Uttar Pradesh',
      country: 'India',
      pincode: '201301',
      imageUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Rohan Kapoor',
      type: 'CUSTOMER',
      email: 'rohan.kapoor@urbanclient.in',
      mobile: '+91 9813456784',
      street: '72 Model Town',
      city: 'Chandigarh',
      state: 'Punjab',
      country: 'India',
      pincode: '160022',
      imageUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Aditya Singhal',
      type: 'CUSTOMER',
      email: 'aditya.singhal@urbanclient.in',
      mobile: '+91 9814567895',
      street: '15 C-Scheme, Ashok Nagar',
      city: 'Jaipur',
      state: 'Rajasthan',
      country: 'India',
      pincode: '302001',
      imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Manish Rawat',
      type: 'CUSTOMER',
      email: 'manish.rawat@urbanclient.in',
      mobile: '+91 9815678906',
      street: 'Rajpur Road near Clock Tower',
      city: 'Dehradun',
      state: 'Uttarakhand',
      country: 'India',
      pincode: '248001',
      imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Harpreet Singh',
      type: 'CUSTOMER',
      email: 'harpreet.singh@urbanclient.in',
      mobile: '+91 9816789017',
      street: 'Mall Road, Civil Lines',
      city: 'Amritsar',
      state: 'Punjab',
      country: 'India',
      pincode: '143001',
      imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Sameer Khanna',
      type: 'CUSTOMER',
      email: 'sameer.khanna@urbanclient.in',
      mobile: '+91 9817890128',
      street: 'Gomti Nagar Extension',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      country: 'India',
      pincode: '226010',
      imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Gaurav Bhatia',
      type: 'CUSTOMER',
      email: 'gaurav.bhatia@urbanclient.in',
      mobile: '+91 9818901239',
      street: 'Sector 15, Urban Estate',
      city: 'Faridabad',
      state: 'Haryana',
      country: 'India',
      pincode: '121007',
      imageUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Nitin Oberoi',
      type: 'CUSTOMER',
      email: 'nitin.oberoi@urbanclient.in',
      mobile: '+91 9819012340',
      street: 'Civil Lines, The Mall',
      city: 'Kanpur',
      state: 'Uttar Pradesh',
      country: 'India',
      pincode: '208001',
      imageUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      status: 'ARCHIVED',
    },

    // West India (10 Male)
    {
      name: 'Nimesh Pathak',
      type: 'CUSTOMER',
      email: 'nimesh.pathak@example.com',
      mobile: '+91 9820098200',
      street: '78 Satellite Road',
      city: 'Ahmedabad',
      state: 'Gujarat',
      country: 'India',
      pincode: '380015',
      imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Devendra Joshi',
      type: 'CUSTOMER',
      email: 'devendra.joshi@urbanclient.in',
      mobile: '+91 9821123452',
      street: 'Flat 12B, Worli Sea Face',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      pincode: '400030',
      imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Tushar Kulkarni',
      type: 'CUSTOMER',
      email: 'tushar.kulkarni@urbanclient.in',
      mobile: '+91 9822234563',
      street: 'Lane 7, Koregaon Park',
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
      pincode: '411001',
      imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Siddharth Shah',
      type: 'CUSTOMER',
      email: 'siddharth.shah@urbanclient.in',
      mobile: '+91 9823345674',
      street: '22 Alkapuri Society',
      city: 'Vadodara',
      state: 'Gujarat',
      country: 'India',
      pincode: '390007',
      imageUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Nilesh Patel',
      type: 'CUSTOMER',
      email: 'nilesh.patel@urbanclient.in',
      mobile: '+91 9824456785',
      street: 'Ring Road, Vesu',
      city: 'Surat',
      state: 'Gujarat',
      country: 'India',
      pincode: '395007',
      imageUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Akash Deshmukh',
      type: 'CUSTOMER',
      email: 'akash.deshmukh@urbanclient.in',
      mobile: '+91 9825567896',
      street: 'College Road, Gangapur',
      city: 'Nashik',
      state: 'Maharashtra',
      country: 'India',
      pincode: '422005',
      imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Pranav Sawant',
      type: 'CUSTOMER',
      email: 'pranav.sawant@urbanclient.in',
      mobile: '+91 9826678907',
      street: 'Pali Hill, Bandra West',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      pincode: '400050',
      imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Kunal Shinde',
      type: 'CUSTOMER',
      email: 'kunal.shinde@urbanclient.in',
      mobile: '+91 9827789018',
      street: 'Baner-Pashan Link Road',
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
      pincode: '411045',
      imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Bhavin Vora',
      type: 'CUSTOMER',
      email: 'bhavin.vora@urbanclient.in',
      mobile: '+91 9828890129',
      street: 'Kalawad Road',
      city: 'Rajkot',
      state: 'Gujarat',
      country: 'India',
      pincode: '360005',
      imageUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Mayur Gaikwad',
      type: 'CUSTOMER',
      email: 'mayur.gaikwad@urbanclient.in',
      mobile: '+91 9829901230',
      street: 'Camp Area',
      city: 'Belgaum',
      state: 'Karnataka',
      country: 'India',
      pincode: '590001',
      imageUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },

    // South India (10 Male)
    {
      name: 'Karthik Ramanathan',
      type: 'CUSTOMER',
      email: 'karthik.ramanathan@urbanclient.in',
      mobile: '+91 9840123451',
      street: '4th Block, Koramangala',
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
      pincode: '560034',
      imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Arjun Nair',
      type: 'CUSTOMER',
      email: 'arjun.nair@urbanclient.in',
      mobile: '+91 9841234562',
      street: 'Marine Drive, Ernakulam',
      city: 'Kochi',
      state: 'Kerala',
      country: 'India',
      pincode: '682031',
      imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Venkat Reddy',
      type: 'CUSTOMER',
      email: 'venkat.reddy@urbanclient.in',
      mobile: '+91 9842345673',
      street: 'Road No 36, Jubilee Hills',
      city: 'Hyderabad',
      state: 'Telangana',
      country: 'India',
      pincode: '500033',
      imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Suresh Menon',
      type: 'CUSTOMER',
      email: 'suresh.menon@urbanclient.in',
      mobile: '+91 9843456784',
      street: 'Boat Club Road, R.A. Puram',
      city: 'Chennai',
      state: 'Tamil Nadu',
      country: 'India',
      pincode: '600028',
      imageUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Pradeep Shenoy',
      type: 'CUSTOMER',
      email: 'pradeep.shenoy@urbanclient.in',
      mobile: '+91 9844567895',
      street: 'Jayalakshmipuram Main Road',
      city: 'Mysuru',
      state: 'Karnataka',
      country: 'India',
      pincode: '570012',
      imageUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Vijay Raghavan',
      type: 'CUSTOMER',
      email: 'vijay.raghavan@urbanclient.in',
      mobile: '+91 9845678906',
      street: 'Race Course Road',
      city: 'Coimbatore',
      state: 'Tamil Nadu',
      country: 'India',
      pincode: '641018',
      imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Manoj Pillai',
      type: 'CUSTOMER',
      email: 'manoj.pillai@urbanclient.in',
      mobile: '+91 9846789017',
      street: 'Kowdiar Avenue',
      city: 'Thiruvananthapuram',
      state: 'Kerala',
      country: 'India',
      pincode: '695003',
      imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Ravichandran Prasad',
      type: 'CUSTOMER',
      email: 'ravi.prasad@urbanclient.in',
      mobile: '+91 9847890128',
      street: 'Siripuram Junction, Waltair',
      city: 'Visakhapatnam',
      state: 'Andhra Pradesh',
      country: 'India',
      pincode: '530003',
      imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Gopal Balakrishnan',
      type: 'CUSTOMER',
      email: 'gopal.balan@urbanclient.in',
      mobile: '+91 9848901239',
      street: 'Indiranagar 100ft Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
      pincode: '560038',
      imageUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Naveen Chander',
      type: 'CUSTOMER',
      email: 'naveen.chander@urbanclient.in',
      mobile: '+91 9849012340',
      street: 'Banjara Hills Road No 12',
      city: 'Hyderabad',
      state: 'Telangana',
      country: 'India',
      pincode: '500034',
      imageUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },

    // East & Central India (5 Male)
    {
      name: 'Sourav Ganguly',
      type: 'CUSTOMER',
      email: 'sourav.ganguly@urbanclient.in',
      mobile: '+91 9830123451',
      street: 'Alipore Park Road',
      city: 'Kolkata',
      state: 'West Bengal',
      country: 'India',
      pincode: '700027',
      imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Amitava Roy',
      type: 'CUSTOMER',
      email: 'amitava.roy@urbanclient.in',
      mobile: '+91 9831234562',
      street: 'Salt Lake Sector 5',
      city: 'Kolkata',
      state: 'West Bengal',
      country: 'India',
      pincode: '700091',
      imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Rajeev Verma',
      type: 'CUSTOMER',
      email: 'rajeev.verma@urbanclient.in',
      mobile: '+91 9832345673',
      street: 'Vijay Nagar Square',
      city: 'Indore',
      state: 'Madhya Pradesh',
      country: 'India',
      pincode: '452010',
      imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Subhashish Patnaik',
      type: 'CUSTOMER',
      email: 'subhashish.patnaik@urbanclient.in',
      mobile: '+91 9833456784',
      street: 'Saheed Nagar',
      city: 'Bhubaneswar',
      state: 'Odisha',
      country: 'India',
      pincode: '751007',
      imageUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Prabhat Mishra',
      type: 'CUSTOMER',
      email: 'prabhat.mishra@urbanclient.in',
      mobile: '+91 9834567895',
      street: 'Boring Road',
      city: 'Patna',
      state: 'Bihar',
      country: 'India',
      pincode: '800001',
      imageUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      status: 'ARCHIVED',
    },

    // Foreign Male (5 Male)
    {
      name: 'James Anderson',
      type: 'CUSTOMER',
      email: 'james.anderson@globalclient.com',
      mobile: '+1 212 555 0143',
      street: '742 Evergreen Terrace, Manhattan',
      city: 'New York',
      state: 'NY',
      country: 'United States',
      pincode: '10021',
      imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Oliver Smith',
      type: 'CUSTOMER',
      email: 'oliver.smith@globalclient.co.uk',
      mobile: '+44 20 7946 0912',
      street: '14 Kensington High Street',
      city: 'London',
      state: 'Greater London',
      country: 'United Kingdom',
      pincode: 'W8 4PT',
      imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Tariq Al-Mansoor',
      type: 'CUSTOMER',
      email: 'tariq.mansoor@globalclient.ae',
      mobile: '+971 4 312 9876',
      street: 'Villa 28, Palm Jumeirah',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
      pincode: '00000',
      imageUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Lucas Brown',
      type: 'CUSTOMER',
      email: 'lucas.brown@globalclient.com.au',
      mobile: '+61 2 9876 5432',
      street: '88 George Street, The Rocks',
      city: 'Sydney',
      state: 'NSW',
      country: 'Australia',
      pincode: '2000',
      imageUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Liam Tremblay',
      type: 'CUSTOMER',
      email: 'liam.tremblay@globalclient.ca',
      mobile: '+1 416 555 7890',
      street: '120 Bay Street, Downtown',
      city: 'Toronto',
      state: 'Ontario',
      country: 'Canada',
      pincode: 'M5J 2R8',
      imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },

    // ---------------------------------------------------------------
    // SECTION B: 40 FEMALE CUSTOMERS (35 Domestic India + 5 Foreign)
    // ---------------------------------------------------------------
    // North India (10 Female)
    {
      name: 'Priya Aggarwal',
      type: 'CUSTOMER',
      email: 'priya.aggarwal@urbanclient.in',
      mobile: '+91 9710123451',
      street: 'D-8 Vasant Vihar',
      city: 'Delhi',
      state: 'Delhi',
      country: 'India',
      pincode: '110057',
      imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Ananya Verma',
      type: 'CUSTOMER',
      email: 'ananya.verma@urbanclient.in',
      mobile: '+91 9711234562',
      street: 'Sushant Lok Phase 1',
      city: 'Gurgaon',
      state: 'Haryana',
      country: 'India',
      pincode: '122009',
      imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Meera Singhania',
      type: 'CUSTOMER',
      email: 'meera.singhania@urbanclient.in',
      mobile: '+91 9712345673',
      street: 'Sector 50, Nirvana Country',
      city: 'Noida',
      state: 'Uttar Pradesh',
      country: 'India',
      pincode: '201307',
      imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Ritu Saxena',
      type: 'CUSTOMER',
      email: 'ritu.saxena@urbanclient.in',
      mobile: '+91 9713456784',
      street: 'Mahanagar Extension',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      country: 'India',
      pincode: '226006',
      imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Kavita Joshi',
      type: 'CUSTOMER',
      email: 'kavita.joshi@urbanclient.in',
      mobile: '+91 9714567895',
      street: 'Malviya Nagar',
      city: 'Jaipur',
      state: 'Rajasthan',
      country: 'India',
      pincode: '302017',
      imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Simran Gill',
      type: 'CUSTOMER',
      email: 'simran.gill@urbanclient.in',
      mobile: '+91 9715678906',
      street: 'Sector 9, Inner Market',
      city: 'Chandigarh',
      state: 'Punjab',
      country: 'India',
      pincode: '160009',
      imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Shalini Bhatnagar',
      type: 'CUSTOMER',
      email: 'shalini.bhatnagar@urbanclient.in',
      mobile: '+91 9716789017',
      street: 'Ballupur Canal Road',
      city: 'Dehradun',
      state: 'Uttarakhand',
      country: 'India',
      pincode: '248001',
      imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Gurpreet Kaur',
      type: 'CUSTOMER',
      email: 'gurpreet.kaur@urbanclient.in',
      mobile: '+91 9717890128',
      street: 'Ranjit Avenue B-Block',
      city: 'Amritsar',
      state: 'Punjab',
      country: 'India',
      pincode: '143001',
      imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Pallavi Gupta',
      type: 'CUSTOMER',
      email: 'pallavi.gupta@urbanclient.in',
      mobile: '+91 9718901239',
      street: 'Swarn Nagari',
      city: 'Greater Noida',
      state: 'Uttar Pradesh',
      country: 'India',
      pincode: '201310',
      imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Nandini Mathur',
      type: 'CUSTOMER',
      email: 'nandini.mathur@urbanclient.in',
      mobile: '+91 9719012340',
      street: 'Sadar Bazar Road',
      city: 'Agra',
      state: 'Uttar Pradesh',
      country: 'India',
      pincode: '282001',
      imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      status: 'ARCHIVED',
    },

    // West India (10 Female)
    {
      name: 'Neha Deshmukh',
      type: 'CUSTOMER',
      email: 'neha.deshmukh@urbanclient.in',
      mobile: '+91 9720123451',
      street: 'Prabhadevi New Link Road',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      pincode: '400025',
      imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Pooja Mehta',
      type: 'CUSTOMER',
      email: 'pooja.mehta@urbanclient.in',
      mobile: '+91 9721234562',
      street: 'Bodakdev, Judges Bungalow Road',
      city: 'Ahmedabad',
      state: 'Gujarat',
      country: 'India',
      pincode: '380054',
      imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Tanvi Shah',
      type: 'CUSTOMER',
      email: 'tanvi.shah@urbanclient.in',
      mobile: '+91 9722234563',
      street: 'Bhandarkar Road, Deccan',
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
      pincode: '411004',
      imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Sneha Sawant',
      type: 'CUSTOMER',
      email: 'sneha.sawant@urbanclient.in',
      mobile: '+91 9723345674',
      street: 'Hiranandani Gardens, Powai',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      pincode: '400076',
      imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Bhumika Trivedi',
      type: 'CUSTOMER',
      email: 'bhumika.trivedi@urbanclient.in',
      mobile: '+91 9724456785',
      street: 'Akota Gardens',
      city: 'Vadodara',
      state: 'Gujarat',
      country: 'India',
      pincode: '390020',
      imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Rupal Chawda',
      type: 'CUSTOMER',
      email: 'rupal.chawda@urbanclient.in',
      mobile: '+91 9725567896',
      street: 'Piplod Main Road',
      city: 'Surat',
      state: 'Gujarat',
      country: 'India',
      pincode: '395007',
      imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Gauri Kadam',
      type: 'CUSTOMER',
      email: 'gauri.kadam@urbanclient.in',
      mobile: '+91 9726678907',
      street: 'Mahatma Nagar',
      city: 'Nashik',
      state: 'Maharashtra',
      country: 'India',
      pincode: '422007',
      imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Archana Tambe',
      type: 'CUSTOMER',
      email: 'archana.tambe@urbanclient.in',
      mobile: '+91 9727789018',
      street: 'Aundh Harmony Enclave',
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
      pincode: '411007',
      imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Payal Doshi',
      type: 'CUSTOMER',
      email: 'payal.doshi@urbanclient.in',
      mobile: '+91 9728890129',
      street: 'University Road',
      city: 'Rajkot',
      state: 'Gujarat',
      country: 'India',
      pincode: '360005',
      imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Kalyani Jadhav',
      type: 'CUSTOMER',
      email: 'kalyani.jadhav@urbanclient.in',
      mobile: '+91 9729901230',
      street: 'Tarabai Park',
      city: 'Kolhapur',
      state: 'Maharashtra',
      country: 'India',
      pincode: '416003',
      imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },

    // South India (10 Female)
    {
      name: 'Deepa Krishnan',
      type: 'CUSTOMER',
      email: 'deepa.krishnan@urbanclient.in',
      mobile: '+91 9740123451',
      street: 'Lavelle Road, Shanthala Nagar',
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
      pincode: '560001',
      imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Swati Iyer',
      type: 'CUSTOMER',
      email: 'swati.iyer@urbanclient.in',
      mobile: '+91 9741234562',
      street: 'Nungambakkam High Road',
      city: 'Chennai',
      state: 'Tamil Nadu',
      country: 'India',
      pincode: '600034',
      imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Lakshmi Pillai',
      type: 'CUSTOMER',
      email: 'lakshmi.pillai@urbanclient.in',
      mobile: '+91 9742345673',
      street: 'Panampilly Nagar',
      city: 'Kochi',
      state: 'Kerala',
      country: 'India',
      pincode: '682036',
      imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Divya Balan',
      type: 'CUSTOMER',
      email: 'divya.balan@urbanclient.in',
      mobile: '+91 9743456784',
      street: 'Madhapur Cyber Hills',
      city: 'Hyderabad',
      state: 'Telangana',
      country: 'India',
      pincode: '500081',
      imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Anupama Hegde',
      type: 'CUSTOMER',
      email: 'anupama.hegde@urbanclient.in',
      mobile: '+91 9744567895',
      street: 'V.V. Mohalla',
      city: 'Mysuru',
      state: 'Karnataka',
      country: 'India',
      pincode: '570002',
      imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Keerthi Sundaram',
      type: 'CUSTOMER',
      email: 'keerthi.sundaram@urbanclient.in',
      mobile: '+91 9745678906',
      street: 'R.S. Puram West',
      city: 'Coimbatore',
      state: 'Tamil Nadu',
      country: 'India',
      pincode: '641002',
      imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Reshma Thomas',
      type: 'CUSTOMER',
      email: 'reshma.thomas@urbanclient.in',
      mobile: '+91 9746789017',
      street: 'Vellayambalam Junction',
      city: 'Thiruvananthapuram',
      state: 'Kerala',
      country: 'India',
      pincode: '695010',
      imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Sravani Rao',
      type: 'CUSTOMER',
      email: 'sravani.rao@urbanclient.in',
      mobile: '+91 9747890128',
      street: 'MVP Colony Sector 2',
      city: 'Visakhapatnam',
      state: 'Andhra Pradesh',
      country: 'India',
      pincode: '530017',
      imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Geetha Varadarajan',
      type: 'CUSTOMER',
      email: 'geetha.rajan@urbanclient.in',
      mobile: '+91 9748901239',
      street: 'Sadashivanagar 11th Cross',
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
      pincode: '560080',
      imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Yamini Reddy',
      type: 'CUSTOMER',
      email: 'yamini.reddy@urbanclient.in',
      mobile: '+91 9749012340',
      street: 'Gachibowli Financial District',
      city: 'Hyderabad',
      state: 'Telangana',
      country: 'India',
      pincode: '500032',
      imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },

    // East & Central India (5 Female)
    {
      name: 'Rina Banerjee',
      type: 'CUSTOMER',
      email: 'rina.banerjee@urbanclient.in',
      mobile: '+91 9730123451',
      street: 'Ballygunge Circular Road',
      city: 'Kolkata',
      state: 'West Bengal',
      country: 'India',
      pincode: '700019',
      imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Ishita Sen',
      type: 'CUSTOMER',
      email: 'ishita.sen@urbanclient.in',
      mobile: '+91 9731234562',
      street: 'New Town Action Area 1',
      city: 'Kolkata',
      state: 'West Bengal',
      country: 'India',
      pincode: '700156',
      imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Shweta Tiwari',
      type: 'CUSTOMER',
      email: 'shweta.tiwari@urbanclient.in',
      mobile: '+91 9732345673',
      street: 'Palasia Main Road',
      city: 'Indore',
      state: 'Madhya Pradesh',
      country: 'India',
      pincode: '452001',
      imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Madhusmita Mohanty',
      type: 'CUSTOMER',
      email: 'madhu.mohanty@urbanclient.in',
      mobile: '+91 9733456784',
      street: 'Patia Infocity Avenue',
      city: 'Bhubaneswar',
      state: 'Odisha',
      country: 'India',
      pincode: '751024',
      imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Debolina Das',
      type: 'CUSTOMER',
      email: 'debolina.das@urbanclient.in',
      mobile: '+91 9734567895',
      street: 'G.S. Road, Christian Basti',
      city: 'Guwahati',
      state: 'Assam',
      country: 'India',
      pincode: '781005',
      imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      status: 'ARCHIVED',
    },

    // Foreign Female (5 Female)
    {
      name: 'Emma Watson',
      type: 'CUSTOMER',
      email: 'emma.watson@globalclient.co.uk',
      mobile: '+44 20 7123 4567',
      street: '45 Chelsea Square',
      city: 'London',
      state: 'Greater London',
      country: 'United Kingdom',
      pincode: 'SW3 6LF',
      imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Sophia Martinez',
      type: 'CUSTOMER',
      email: 'sophia.martinez@globalclient.com',
      mobile: '+1 415 555 0198',
      street: '320 Marina Blvd',
      city: 'San Francisco',
      state: 'CA',
      country: 'United States',
      pincode: '94123',
      imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Fatima Zahra',
      type: 'CUSTOMER',
      email: 'fatima.zahra@globalclient.ae',
      mobile: '+971 4 876 5432',
      street: 'Downtown Boulevard Tower A',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
      pincode: '00000',
      imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Elena Müller',
      type: 'CUSTOMER',
      email: 'elena.mueller@globalclient.de',
      mobile: '+49 30 1234 5678',
      street: 'Friedrichstraße 120',
      city: 'Berlin',
      state: 'Berlin',
      country: 'Germany',
      pincode: '10117',
      imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Mei-Ling Tan',
      type: 'CUSTOMER',
      email: 'meiling.tan@globalclient.sg',
      mobile: '+65 6789 0123',
      street: '15 Orchard Boulevard',
      city: 'Singapore',
      state: 'Central Region',
      country: 'Singapore',
      pincode: '248645',
      imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },

    // -------------------------------------------------------------------
    // SECTION C: 20 CORPORATE & COMMERCIAL CUSTOMERS (10 India + 10 Foreign)
    // -------------------------------------------------------------------
    // Domestic Corporate (10 B2B)
    {
      name: 'Urban Nest Interior Architects LLP',
      type: 'CUSTOMER',
      email: 'procurement@urbannest.in',
      mobile: '+91 22 2490 1234',
      street: 'Level 8, Godrej One, Vikhroli East',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      pincode: '400079',
      imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Horizon Tech Workspace Labs Ltd',
      type: 'CUSTOMER',
      email: 'facilities@horizontech.co.in',
      mobile: '+91 80 4123 5678',
      street: 'Ecospace Business Park, Bellandur',
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
      pincode: '560103',
      imageUrl: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Zenith Collaborative Co-Working Hubs',
      type: 'CUSTOMER',
      email: 'admin@zenithspaces.in',
      mobile: '+91 124 456 7890',
      street: 'Cyber City Tower 10B',
      city: 'Gurgaon',
      state: 'Haryana',
      country: 'India',
      pincode: '122002',
      imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Aura Luxury Hospitality Suites',
      type: 'CUSTOMER',
      email: 'projects@aurasuites.com',
      mobile: '+91 40 6789 0123',
      street: 'Financial District, Nanakramguda',
      city: 'Hyderabad',
      state: 'Telangana',
      country: 'India',
      pincode: '500032',
      imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Vanguard Realty & Living Spaces',
      type: 'CUSTOMER',
      email: 'info@vanguardliving.in',
      mobile: '+91 44 2811 4321',
      street: 'Express Avenue Commercial Tower',
      city: 'Chennai',
      state: 'Tamil Nadu',
      country: 'India',
      pincode: '600002',
      imageUrl: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'MetroMatrix Corporate Towers',
      type: 'CUSTOMER',
      email: 'contact@metromatrix.in',
      mobile: '+91 20 6601 2345',
      street: 'Pancard Club Road, Baner',
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
      pincode: '411045',
      imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Oasis Wellness & Boutique Resorts',
      type: 'CUSTOMER',
      email: 'sourcing@oasisresorts.in',
      mobile: '+91 832 245 6789',
      street: 'Candolim Beach Road',
      city: 'Panaji',
      state: 'Goa',
      country: 'India',
      pincode: '403515',
      imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'PrimeStone Infrastructure & Design',
      type: 'CUSTOMER',
      email: 'vendorcare@primestone.in',
      mobile: '+91 79 2685 1122',
      street: 'SG Highway Commercial Complex',
      city: 'Ahmedabad',
      state: 'Gujarat',
      country: 'India',
      pincode: '380054',
      imageUrl: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Heritage Grand Hotels & Resorts',
      type: 'CUSTOMER',
      email: 'interiors@heritagegrand.in',
      mobile: '+91 294 242 8899',
      street: 'Lake Palace Road',
      city: 'Udaipur',
      state: 'Rajasthan',
      country: 'India',
      pincode: '313001',
      imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Apex SmartOffices India Pvt Ltd',
      type: 'CUSTOMER',
      email: 'accounts@apexsmartoffices.in',
      mobile: '+91 120 405 6789',
      street: 'Logix City Centre, Sector 32',
      city: 'Noida',
      state: 'Uttar Pradesh',
      country: 'India',
      pincode: '201301',
      imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },

    // Foreign Corporate (10 B2B)
    {
      name: 'Apex Architectural Studio LLC',
      type: 'CUSTOMER',
      email: 'procurement@apexstudio.nyc',
      mobile: '+1 212 908 1234',
      street: '350 5th Ave, Empire State Suite 42',
      city: 'New York',
      state: 'NY',
      country: 'United States',
      pincode: '10118',
      imageUrl: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Silicon Valley Innovations Workspace Inc',
      type: 'CUSTOMER',
      email: 'facilities@svinnovations.io',
      mobile: '+1 650 493 0123',
      street: '3000 Sand Hill Road',
      city: 'Menlo Park',
      state: 'CA',
      country: 'United States',
      pincode: '94025',
      imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Mayfair Commercial Interiors Ltd',
      type: 'CUSTOMER',
      email: 'enquiries@mayfairinteriors.co.uk',
      mobile: '+44 20 7839 9000',
      street: '12 Berkeley Square, Mayfair',
      city: 'London',
      state: 'Greater London',
      country: 'United Kingdom',
      pincode: 'W1J 6BD',
      imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Emirates Modern Hospitality Group LLC',
      type: 'CUSTOMER',
      email: 'purchasing@emirateshospitality.ae',
      mobile: '+971 4 209 8765',
      street: 'Sheikh Zayed Road, DIFC Tower 2',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
      pincode: '00000',
      imageUrl: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Marina Bay Workspace Solutions Pte Ltd',
      type: 'CUSTOMER',
      email: 'office@marinabaysolutions.sg',
      mobile: '+65 6812 3456',
      street: '10 Marina Boulevard, Tower 2',
      city: 'Singapore',
      state: 'Central Region',
      country: 'Singapore',
      pincode: '018983',
      imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Nordic Habitat & Living GmbH',
      type: 'CUSTOMER',
      email: 'einkauf@nordichabitat.de',
      mobile: '+49 89 2345 6789',
      street: 'Maximilianstraße 35',
      city: 'Munich',
      state: 'Bavaria',
      country: 'Germany',
      pincode: '80539',
      imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Pacific Rim Commercial Properties Ltd',
      type: 'CUSTOMER',
      email: 'projects@pacificrimproperties.com.au',
      mobile: '+61 3 9654 3210',
      street: '101 Collins Street',
      city: 'Melbourne',
      state: 'VIC',
      country: 'Australia',
      pincode: '3000',
      imageUrl: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Maple Leaf Corporate Furnishings Inc',
      type: 'CUSTOMER',
      email: 'supply@maplefurnishings.ca',
      mobile: '+1 604 688 1234',
      street: '1055 West Georgia Street',
      city: 'Vancouver',
      state: 'BC',
      country: 'Canada',
      pincode: 'V6E 3P3',
      imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Atelier Parisien Mobilier SAS',
      type: 'CUSTOMER',
      email: 'contact@atelierparisien.fr',
      mobile: '+33 1 42 68 55 00',
      street: '28 Boulevard Haussmann',
      city: 'Paris',
      state: 'Île-de-France',
      country: 'France',
      pincode: '75009',
      imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=150&auto=format&fit=crop&q=80',
      status: 'ACTIVE',
    },
    {
      name: 'Tokyo Urban Design & Architecture KK',
      type: 'CUSTOMER',
      email: 'info@tokyourbandesign.jp',
      mobile: '+81 3 5555 0147',
      street: 'Roppongi Hills Mori Tower 24F',
      city: 'Tokyo',
      state: 'Kanto',
      country: 'Japan',
      pincode: '106-6124',
      imageUrl: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=150&auto=format&fit=crop&q=80',
      status: 'ARCHIVED',
    },
  ];

  for (const cust of customersData) {
    contacts[cust.name] = await prisma.contact.upsert({
      where: { email: cust.email },
      update: cust,
      create: cust,
    });
  }

  // ==========================================
  // 6. Users (Admin, Accountant, Contact User)
  // ==========================================
  console.log('Seeding Users...');
  const adminPassword = await bcrypt.hash('Admin@123456', 10);
  const accountantPassword = await bcrypt.hash('Account@123456', 10);
  const userPassword = await bcrypt.hash('User@123456', 10);

  // Admin
  await prisma.user.upsert({
    where: { loginId: 'admin' },
    update: { passwordHash: adminPassword },
    create: {
      loginId: 'admin',
      name: 'Administrator',
      email: 'admin@urbanfurniture.com',
      passwordHash: adminPassword,
      role: 'ADMIN',
      status: 'ACTIVE',
    },
  });

  // Accountant
  await prisma.user.upsert({
    where: { loginId: 'accountant' },
    update: { passwordHash: accountantPassword },
    create: {
      loginId: 'accountant',
      name: 'Invoicing User (Accountant)',
      email: 'accountant@urbanfurniture.com',
      passwordHash: accountantPassword,
      role: 'ACCOUNTANT',
      status: 'ACTIVE',
    },
  });

  // Contact User for Nimesh Pathak
  if (contacts['Nimesh Pathak']) {
    await prisma.user.upsert({
      where: { loginId: 'nimesh' },
      update: { passwordHash: userPassword, contactId: contacts['Nimesh Pathak'].id },
      create: {
        loginId: 'nimesh',
        name: 'Nimesh Pathak',
        email: 'nimesh.pathak@example.com',
        passwordHash: userPassword,
        role: 'CONTACT_USER',
        contactId: contacts['Nimesh Pathak'].id,
        status: 'ACTIVE',
      },
    });
  }

  // ==========================================
  // 7. Analytic Accounts
  // ==========================================
  console.log('Seeding Analytic Accounts...');
  const analyticsData = [
    { name: 'Furniture Operations', type: 'EXPENSE' },
    { name: 'Project 1', type: 'EXPENSE' },
    { name: 'Corporate Commercial Sales', type: 'INCOME' },
  ];

  const analytics = {};
  for (const an of analyticsData) {
    analytics[an.name] = await prisma.analyticAccount.upsert({
      where: { name: an.name },
      update: { type: an.type },
      create: an,
    });
  }

  // ==========================================
  // 8. Demo Budget
  // ==========================================
  console.log('Seeding Demo Budget...');
  const existingBudget = await prisma.budget.findFirst({
    where: { name: 'January 2026 Operations' },
  });

  if (!existingBudget && contacts['Rahul Sharma'] && analytics['Furniture Operations']) {
    await prisma.budget.create({
      data: {
        name: 'January 2026 Operations',
        startDate: new Date('2026-01-01T00:00:00Z'),
        endDate: new Date('2026-01-31T23:59:59Z'),
        responsibleId: contacts['Rahul Sharma'].id,
        analyticAccountId: analytics['Furniture Operations'].id,
        type: 'EXPENSE',
        committedAmount: 200000.0,
        status: 'CONFIRMED',
        notes: 'Monthly furniture procurement & maintenance budget',
      },
    });
  }

  console.log('--- Urban Furniture Database Seeding Completed Successfully! ---');
  console.log(`Seeded Categories: ${Object.keys(categories).length}`);
  console.log(`Seeded Products: ${productsData.length}`);
  console.log(`Seeded Customers: ${customersData.length}`);
  console.log(`Seeded Vendors: ${vendorsData.length}`);
}

main()
  .catch((e) => {
    console.error('Seeding error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
