import PDFDocument from 'pdfkit';
import prisma from '../../prisma/client.js';

const BRAND = {
  primary: '#714B67',
  secondary: '#017E84',
  dark: '#1e293b',
  gray: '#64748b',
  light: '#f8fafc',
  border: '#e2e8f0'
};

function drawHeader(doc, title, number, date, company = 'Urban Furniture') {
  // Background bar
  doc.rect(0, 0, doc.page.width, 80).fill(BRAND.primary);

  // Company name
  doc.fillColor('#ffffff').fontSize(20).font('Helvetica-Bold')
    .text(company, 40, 20);
  doc.fontSize(10).font('Helvetica').fillColor('rgba(255,255,255,0.8)')
    .text('Accounting & ERP System', 40, 46);

  // Document type + number
  doc.fontSize(22).font('Helvetica-Bold').fillColor('#ffffff')
    .text(title, 0, 20, { align: 'right', width: doc.page.width - 40 });
  doc.fontSize(11).font('Helvetica').fillColor('rgba(255,255,255,0.8)')
    .text(number, 0, 48, { align: 'right', width: doc.page.width - 40 });

  doc.moveDown(1);
}

function drawInfoBox(doc, yStart, leftLabel, leftValue, rightLabel, rightValue) {
  const boxY = yStart;
  const midX = (doc.page.width - 80) / 2 + 40;

  doc.rect(40, boxY, doc.page.width - 80, 60).fill(BRAND.light).stroke(BRAND.border);

  doc.fillColor(BRAND.gray).fontSize(8).font('Helvetica-Bold')
    .text(leftLabel.toUpperCase(), 55, boxY + 10);
  doc.fillColor(BRAND.dark).fontSize(11).font('Helvetica-Bold')
    .text(leftValue, 55, boxY + 23, { width: (doc.page.width - 80) / 2 - 20 });

  doc.fillColor(BRAND.gray).fontSize(8).font('Helvetica-Bold')
    .text(rightLabel.toUpperCase(), midX + 10, boxY + 10);
  doc.fillColor(BRAND.dark).fontSize(11).font('Helvetica-Bold')
    .text(rightValue, midX + 10, boxY + 23);

  return boxY + 75;
}

function drawLinesTable(doc, yStart, lines, hasTax = false) {
  const colX = hasTax
    ? { desc: 40, qty: 270, price: 340, tax: 400, subtotal: 470 }
    : { desc: 40, qty: 310, price: 400, subtotal: 480 };
  const tableWidth = doc.page.width - 80;

  // Header row
  doc.rect(40, yStart, tableWidth, 24).fill(BRAND.primary);
  doc.fillColor('#ffffff').fontSize(9).font('Helvetica-Bold');
  doc.text('DESCRIPTION', colX.desc + 5, yStart + 7);
  doc.text('QTY', colX.qty, yStart + 7);
  doc.text('UNIT PRICE', colX.price, yStart + 7);
  if (hasTax) doc.text('TAX %', colX.tax, yStart + 7);
  doc.text('SUBTOTAL', colX.subtotal, yStart + 7, { align: 'right', width: doc.page.width - 40 - colX.subtotal - 5 });

  let y = yStart + 24;
  let subtotal = 0;
  let totalTax = 0;

  lines.forEach((line, i) => {
    const rowH = 22;
    const bg = i % 2 === 0 ? '#ffffff' : BRAND.light;
    doc.rect(40, y, tableWidth, rowH).fill(bg);

    const qty = parseFloat(line.quantity || 1);
    const price = parseFloat(line.unit_price || 0);
    const taxRate = parseFloat(line.tax_rate || 0);
    const lineSub = qty * price;
    const lineTax = lineSub * (taxRate / 100);
    subtotal += lineSub;
    totalTax += lineTax;

    doc.fillColor(BRAND.dark).fontSize(9).font('Helvetica');
    doc.text(line.description || line.product?.name || '—', colX.desc + 5, y + 6, { width: colX.qty - colX.desc - 10 });
    doc.text(qty.toFixed(2), colX.qty, y + 6);
    doc.text(`$${price.toFixed(2)}`, colX.price, y + 6);
    if (hasTax) doc.text(`${taxRate.toFixed(1)}%`, colX.tax, y + 6);
    doc.text(`$${lineSub.toFixed(2)}`, colX.subtotal, y + 6, { align: 'right', width: doc.page.width - 40 - colX.subtotal - 5 });

    y += rowH;
  });

  // Totals block
  y += 8;
  const totalsX = doc.page.width - 200;

  const addTotal = (label, amount, bold = false, highlight = false) => {
    if (highlight) doc.rect(totalsX - 5, y - 2, 165, 22).fill(BRAND.primary);
    doc.fillColor(highlight ? '#ffffff' : (bold ? BRAND.dark : BRAND.gray))
      .fontSize(bold || highlight ? 10 : 9)
      .font(bold || highlight ? 'Helvetica-Bold' : 'Helvetica');
    doc.text(label, totalsX, y, { width: 90 });
    doc.text(`$${parseFloat(amount).toFixed(2)}`, totalsX + 90, y, { align: 'right', width: 70 });
    y += 22;
  };

  addTotal('Subtotal', subtotal);
  if (hasTax && totalTax > 0) addTotal('Tax', totalTax);
  addTotal('TOTAL', subtotal + totalTax, true, true);

  return y;
}

function drawFooter(doc, notes) {
  const y = doc.page.height - 80;
  doc.rect(0, y, doc.page.width, 80).fill(BRAND.light);
  doc.moveTo(40, y + 1).lineTo(doc.page.width - 40, y + 1).lineWidth(1).strokeColor(BRAND.border).stroke();

  if (notes) {
    doc.fillColor(BRAND.gray).fontSize(8).font('Helvetica-Bold').text('NOTES', 40, y + 12);
    doc.fillColor(BRAND.dark).fontSize(8).font('Helvetica').text(notes, 40, y + 24, { width: doc.page.width - 80 });
  }

  doc.fillColor(BRAND.gray).fontSize(8).font('Helvetica')
    .text(`Generated by Urban Furniture ERP · ${new Date().toLocaleDateString()}`, 0, y + 55, { align: 'center' });
}

// ─── Generate Invoice PDF ──────────────────────────────────────────────────
export const generateInvoicePDF = async (req, res) => {
  try {
    const invoice = await prisma.customerInvoice.findUnique({
      where: { id: Number(req.params.id) },
      include: { customer: true, lines: { include: { product: true } } }
    });
    if (!invoice) return res.status(404).json({ message: 'Invoice not found' });

    const doc = new PDFDocument({ margin: 0, size: 'A4' });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${invoice.invoice_number}.pdf"`);
    doc.pipe(res);

    drawHeader(doc, 'INVOICE', invoice.invoice_number, invoice.invoice_date);

    let y = 100;
    y = drawInfoBox(doc, y,
      'Bill To', `${invoice.customer.name}\n${invoice.customer.email || ''}`,
      'Invoice Date', new Date(invoice.invoice_date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    );

    if (invoice.due_date) {
      y = drawInfoBox(doc, y,
        'Status', invoice.status.replace('_', ' ').toUpperCase(),
        'Due Date', new Date(invoice.due_date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
      );
    }

    y += 10;
    y = drawLinesTable(doc, y, invoice.lines, true);

    if (invoice.paid_amount > 0) {
      y += 8;
      doc.fillColor(BRAND.secondary).fontSize(9).font('Helvetica-Bold')
        .text(`Amount Paid: $${parseFloat(invoice.paid_amount).toFixed(2)}`, 40, y);
      doc.text(`Outstanding: $${parseFloat(invoice.outstanding_amount).toFixed(2)}`, 200, y);
    }

    drawFooter(doc, null);
    doc.end();
  } catch (error) {
    res.status(500).json({ message: 'PDF generation failed', error: error.message });
  }
};

// ─── Generate Vendor Bill PDF ──────────────────────────────────────────────
export const generateBillPDF = async (req, res) => {
  try {
    const bill = await prisma.vendorBill.findUnique({
      where: { id: Number(req.params.id) },
      include: { vendor: true, lines: { include: { product: true } } }
    });
    if (!bill) return res.status(404).json({ message: 'Bill not found' });

    const doc = new PDFDocument({ margin: 0, size: 'A4' });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${bill.bill_number}.pdf"`);
    doc.pipe(res);

    drawHeader(doc, 'VENDOR BILL', bill.bill_number, bill.invoice_date);

    let y = 100;
    y = drawInfoBox(doc, y,
      'Vendor', `${bill.vendor.name}\n${bill.vendor.email || ''}`,
      'Invoice Date', new Date(bill.invoice_date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    );
    y = drawInfoBox(doc, y,
      'Status', bill.status.replace('_', ' ').toUpperCase(),
      'Due Date', bill.due_date ? new Date(bill.due_date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }) : 'N/A'
    );

    y += 10;
    y = drawLinesTable(doc, y, bill.lines, false);

    if (parseFloat(bill.paid_amount) > 0) {
      y += 8;
      doc.fillColor(BRAND.secondary).fontSize(9).font('Helvetica-Bold')
        .text(`Amount Paid: $${parseFloat(bill.paid_amount).toFixed(2)}`, 40, y);
      doc.text(`Outstanding: $${parseFloat(bill.outstanding_amount).toFixed(2)}`, 200, y);
    }

    drawFooter(doc, null);
    doc.end();
  } catch (error) {
    res.status(500).json({ message: 'PDF generation failed', error: error.message });
  }
};

// ─── Generate Purchase Order PDF ───────────────────────────────────────────
export const generatePurchaseOrderPDF = async (req, res) => {
  try {
    const po = await prisma.purchaseOrder.findUnique({
      where: { id: Number(req.params.id) },
      include: { vendor: true, lines: { include: { product: true } } }
    });
    if (!po) return res.status(404).json({ message: 'Purchase order not found' });

    const doc = new PDFDocument({ margin: 0, size: 'A4' });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${po.po_number}.pdf"`);
    doc.pipe(res);

    drawHeader(doc, 'PURCHASE ORDER', po.po_number, po.date);

    let y = 100;
    y = drawInfoBox(doc, y,
      'Vendor', `${po.vendor.name}\n${po.vendor.email || ''}`,
      'Order Date', new Date(po.date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    );
    y = drawInfoBox(doc, y,
      'Status', po.status.toUpperCase(),
      'PO Number', po.po_number
    );

    y += 10;
    y = drawLinesTable(doc, y, po.lines, false);

    if (po.notes) {
      y += 8;
      doc.fillColor(BRAND.gray).fontSize(9).font('Helvetica')
        .text(`Notes: ${po.notes}`, 40, y, { width: doc.page.width - 80 });
    }

    drawFooter(doc, po.notes);
    doc.end();
  } catch (error) {
    res.status(500).json({ message: 'PDF generation failed', error: error.message });
  }
};
