import React, { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import api from '../../services/api';
import { CustomerInvoice, PaymentMethod } from '../../types';
import { 
  FileText, 
  CreditCard, 
  CheckCircle2, 
  Clock, 
  ShieldCheck, 
  Printer, 
  X, 
  AlertCircle,
  Building2
} from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { Pagination } from '../../components/ui/Pagination';

export const PortalInvoicesPage: React.FC = () => {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  const [payModalOpen, setPayModalOpen] = useState(false);
  const [selectedInvoice, setSelectedInvoice] = useState<CustomerInvoice | null>(null);
  const [payMethod, setPayMethod] = useState<PaymentMethod>('BANK');
  const [payAmount, setPayAmount] = useState<number>(0);
  const [paymentSuccess, setPaymentSuccess] = useState(false);
  const [currentPage, setCurrentPage] = useState(1);

  // Fetch Invoices for logged-in contact user
  const { data: invoices, isLoading } = useQuery<CustomerInvoice[]>({
    queryKey: ['portal-invoices'],
    queryFn: async () => {
      const res = await api.get('/invoices');
      return res.data.data;
    },
  });

  // Fetch bank journals to allocate payment
  const { data: journals } = useQuery({
    queryKey: ['journals-list'],
    queryFn: async () => {
      const res = await api.get('/journals');
      return res.data.data;
    },
  });

  const payMutation = useMutation({
    mutationFn: async (payload: any) => {
      const res = await api.post('/payments', payload);
      return res.data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['portal-invoices'] });
      setPaymentSuccess(true);
      setTimeout(() => {
        setPaymentSuccess(false);
        setPayModalOpen(false);
        setSelectedInvoice(null);
      }, 1800);
    },
    onError: (err: any) => {
      alert(err.response?.data?.message || 'Payment processing failed.');
    },
  });

  const handleOpenPay = (inv: CustomerInvoice) => {
    setSelectedInvoice(inv);
    setPayAmount(Number(inv.amountDue));
    setPayModalOpen(true);
    setPaymentSuccess(false);
  };

  const handleProcessPayment = (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedInvoice) return;

    const targetJournal = journals?.find((j: any) => j.type === payMethod) || journals?.[0];

    payMutation.mutate({
      type: 'CUSTOMER',
      partnerId: selectedInvoice.customerId,
      amount: payAmount,
      paymentMethod: payMethod,
      journalId: targetJournal ? targetJournal.id : 1,
      paymentDate: new Date().toISOString().split('T')[0],
      reference: `PORTAL-PAY-${Date.now().toString().slice(-6)}`,
      notes: 'Online customer portal settlement',
      customerInvoiceId: selectedInvoice.id,
    });
  };

  return (
    <div className="space-y-6 max-w-6xl mx-auto">
      {/* Welcome Banner */}
      <div className="bg-gradient-to-r from-[#714B67] to-[#4c2f44] text-white p-6 rounded-2xl shadow-md flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <span className="text-xs uppercase tracking-wider font-semibold text-purple-200 block mb-1">
            Customer Self-Service Portal
          </span>
          <h1 className="text-2xl font-bold">Welcome, {user?.name || 'Customer'}</h1>
          <p className="text-sm text-purple-100 mt-1">
            Review your outstanding invoices, view payment histories, and make instant online payments.
          </p>
        </div>
        <div className="flex items-center gap-2 bg-white/10 px-4 py-2 rounded-xl text-xs backdrop-blur-xs">
          <ShieldCheck className="w-5 h-5 text-emerald-400" />
          <span>256-Bit Encrypted Secure Gateway</span>
        </div>
      </div>

      {/* Invoices List */}
      <div className="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden">
        <div className="p-6 border-b border-gray-100 flex items-center justify-between">
          <h2 className="text-lg font-bold text-gray-900 flex items-center gap-2">
            <FileText className="w-5 h-5 text-[#714B67]" />
            Your Invoices
          </h2>
          <span className="text-xs text-gray-500 font-medium">
            Total {invoices?.length || 0} Invoices
          </span>
        </div>

        {isLoading ? (
          <div className="p-12 text-center text-gray-500">Loading your invoices...</div>
        ) : !invoices || invoices.length === 0 ? (
          <div className="p-12 text-center">
            <FileText className="w-12 h-12 text-gray-300 mx-auto mb-3" />
            <p className="text-gray-600 font-medium">No invoices found for your account</p>
            <p className="text-gray-400 text-sm mt-1">
              New invoices generated by Urban Furniture Accounting will appear here.
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse text-sm">
              <thead>
                <tr className="border-b border-gray-200 bg-gray-50 text-gray-600 text-xs font-semibold uppercase tracking-wider">
                  <th className="py-3 px-4">Invoice #</th>
                  <th className="py-3 px-4">Date</th>
                  <th className="py-3 px-4">Due Date</th>
                  <th className="py-3 px-4">Total Amount</th>
                  <th className="py-3 px-4">Paid to Date</th>
                  <th className="py-3 px-4">Balance Due</th>
                  <th className="py-3 px-4">Status</th>
                  <th className="py-3 px-4 text-right">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {(invoices?.slice((currentPage - 1) * 10, currentPage * 10) || []).map((inv) => (
                  <tr key={inv.id} className="hover:bg-gray-50/70 transition-colors">
                    <td className="py-4 px-4 font-semibold text-[#714B67]">
                      {inv.invoiceNumber}
                    </td>
                    <td className="py-4 px-4 text-gray-600">
                      {new Date(inv.invoiceDate).toLocaleDateString()}
                    </td>
                    <td className="py-4 px-4 text-gray-600">
                      {new Date(inv.dueDate).toLocaleDateString()}
                    </td>
                    <td className="py-4 px-4 font-semibold text-gray-900">
                      ₹{Number(inv.totalAmount).toLocaleString('en-IN', { minimumFractionDigits: 2 })}
                    </td>
                    <td className="py-4 px-4 font-semibold text-emerald-700">
                      ₹{Number(inv.paidAmount).toLocaleString('en-IN', { minimumFractionDigits: 2 })}
                    </td>
                    <td className="py-4 px-4 font-bold text-rose-600">
                      ₹{Number(inv.amountDue).toLocaleString('en-IN', { minimumFractionDigits: 2 })}
                    </td>
                    <td className="py-4 px-4">
                      {inv.status === 'PAID' ? (
                        <span className="inline-flex items-center gap-1 text-xs font-semibold text-emerald-700 bg-emerald-50 border border-emerald-200 px-2.5 py-0.5 rounded-full">
                          <CheckCircle2 className="w-3 h-3" />
                          Paid
                        </span>
                      ) : inv.status === 'POSTED' || inv.status === 'PARTIALLY_PAID' ? (
                        <span className="inline-flex items-center gap-1 text-xs font-semibold text-amber-700 bg-amber-50 border border-amber-200 px-2.5 py-0.5 rounded-full">
                          <Clock className="w-3 h-3" />
                          Payment Due
                        </span>
                      ) : (
                        <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-gray-100 text-gray-600">
                          {inv.status}
                        </span>
                      )}
                    </td>
                    <td className="py-4 px-4 text-right">
                      {Number(inv.amountDue) > 0 && inv.status !== 'DRAFT' && inv.status !== 'CANCELLED' ? (
                        <button
                          onClick={() => handleOpenPay(inv)}
                          className="px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg text-xs font-bold shadow-sm transition-all flex items-center gap-1.5 ml-auto"
                        >
                          <CreditCard className="w-3.5 h-3.5" />
                          Pay Now
                        </button>
                      ) : (
                        <span className="text-xs text-gray-400 font-medium">Settled</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
        {invoices && invoices.length > 0 && (
          <Pagination
            currentPage={currentPage}
            totalItems={invoices.length}
            onPageChange={setCurrentPage}
          />
        )}
      </div>

      {/* Pay Now Modal */}
      {payModalOpen && selectedInvoice && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-xs flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-2xl shadow-2xl max-w-md w-full overflow-hidden animate-in fade-in zoom-in-95 duration-150">
            {paymentSuccess ? (
              <div className="p-8 text-center space-y-3">
                <div className="w-16 h-16 bg-emerald-100 text-emerald-600 rounded-full flex items-center justify-center mx-auto animate-bounce">
                  <CheckCircle2 className="w-10 h-10" />
                </div>
                <h3 className="text-xl font-bold text-gray-900">Payment Successful!</h3>
                <p className="text-sm text-gray-600">
                  Your payment of ₹{payAmount.toLocaleString('en-IN', { minimumFractionDigits: 2 })} has been reconciled with invoice{' '}
                  <strong className="text-gray-900">{selectedInvoice.invoiceNumber}</strong>.
                </p>
                <div className="text-xs text-gray-400">Updating ledger balances...</div>
              </div>
            ) : (
              <>
                <div className="p-6 border-b border-gray-100 flex items-center justify-between bg-gray-50/50">
                  <div className="flex items-center gap-3">
                    <div className="p-2.5 bg-emerald-100 text-emerald-700 rounded-xl">
                      <CreditCard className="w-6 h-6" />
                    </div>
                    <div>
                      <h2 className="text-lg font-bold text-gray-900">Online Invoice Payment</h2>
                      <p className="text-xs text-gray-500 mt-0.5">{selectedInvoice.invoiceNumber}</p>
                    </div>
                  </div>
                  <button
                    onClick={() => setPayModalOpen(false)}
                    className="p-1.5 text-gray-400 hover:text-gray-600 rounded-lg hover:bg-gray-100"
                  >
                    <X className="w-5 h-5" />
                  </button>
                </div>

                <form onSubmit={handleProcessPayment} className="p-6 space-y-4">
                  <div className="p-4 bg-purple-50 border border-purple-100 rounded-xl text-xs space-y-1.5">
                    <div className="flex justify-between text-purple-900">
                      <span>Total Invoice Amount:</span>
                      <span className="font-semibold">₹{Number(selectedInvoice.totalAmount).toLocaleString('en-IN', { minimumFractionDigits: 2 })}</span>
                    </div>
                    <div className="flex justify-between text-purple-900">
                      <span>Outstanding Balance Due:</span>
                      <span className="font-bold text-rose-600">₹{Number(selectedInvoice.amountDue).toLocaleString('en-IN', { minimumFractionDigits: 2 })}</span>
                    </div>
                  </div>

                  <div>
                    <label className="block text-xs font-semibold text-gray-700 mb-1">
                      Choose Payment Method
                    </label>
                    <div className="grid grid-cols-2 gap-2">
                      <button
                        type="button"
                        onClick={() => setPayMethod('BANK')}
                        className={`py-2 px-3 rounded-lg text-xs font-semibold border transition-all ${
                          payMethod === 'BANK'
                            ? 'border-[#714B67] bg-[#714B67]/5 text-[#714B67]'
                            : 'border-gray-200 text-gray-600 hover:bg-gray-50'
                        }`}
                      >
                        Net Banking / UPI
                      </button>
                      <button
                        type="button"
                        onClick={() => setPayMethod('CASH')}
                        className={`py-2 px-3 rounded-lg text-xs font-semibold border transition-all ${
                          payMethod === 'CASH'
                            ? 'border-[#714B67] bg-[#714B67]/5 text-[#714B67]'
                            : 'border-gray-200 text-gray-600 hover:bg-gray-50'
                        }`}
                      >
                        Cash Counter
                      </button>
                    </div>
                  </div>

                  <div>
                    <label className="block text-xs font-semibold text-gray-700 mb-1">
                      Amount to Pay (₹) *
                    </label>
                    <input
                      type="number"
                      step="0.01"
                      min="0.01"
                      max={Number(selectedInvoice.amountDue)}
                      value={payAmount}
                      onChange={(e) => setPayAmount(Number(e.target.value))}
                      className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm font-semibold focus:ring-2 focus:ring-[#714B67]"
                      required
                    />
                  </div>

                  <div className="pt-4 border-t border-gray-100 flex justify-end gap-2">
                    <button
                      type="button"
                      onClick={() => setPayModalOpen(false)}
                      className="px-4 py-2 bg-gray-200 hover:bg-gray-300 text-gray-800 rounded-lg text-xs font-medium"
                    >
                      Cancel
                    </button>
                    <button
                      type="submit"
                      disabled={payMutation.isPending}
                      className="px-5 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg text-xs font-bold shadow-sm"
                    >
                      {payMutation.isPending ? 'Processing...' : `Pay ₹${payAmount.toLocaleString('en-IN', { minimumFractionDigits: 2 })} Now`}
                    </button>
                  </div>
                </form>
              </>
            )}
          </div>
        </div>
      )}
    </div>
  );
};
